# Generated by Django 6.0.4 on 2026-06-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_informacionempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la empresa')),
                ('nif', models.CharField(max_length=20, unique=True, verbose_name='NIF / CIF')),
                ('contacto_nombre', models.CharField(max_length=100, verbose_name='Persona de contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='Email corporativo')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
